language: cpp
dist: xenial
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential cmake qtbase5-dev qttools5-dev qttools5-dev-tools libpoppler-qt5-dev preview-latex-style
script: mkdir -p buildqt && cd buildqt && QT_SELECT=5 qmake ../qtikz.pro && QT_SELECT=5  make && cd ..
# The full build script with Qt and KDE builds fails for now, see https://travis-ci.org/fhackenberger/ktikz/builds/265616161
# script: mkdir -p buildqt && cd buildqt && qmake ../qtikz.pro && make && cd .. && git clean -f -d && mkdir -p build && cd build && cmake -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix` .. && make
